version: "3"

services:
  gitql-api:
    container_name: gitql-api
    image: alanmpinder/gitql-api:latest
    ports:
      - "3000:3000"
    environment:
      - GIT_URL=https://github.com/alanapz/gitql-api.git
      - GIT_BRANCH=main
      - HOST_WORKSPACE_ROOT
      - CORS_ORIGIN
    volumes:
      - "gitql-api-data:/gitql-api"
      - "${HOST_WORKSPACE_ROOT}:/workspace"

volumes:
  gitql-api-data:
    driver: local
