version: "3"

services:
  gitql-api:
    container_name: gitql-api
    image: alanmpinder/gitql-api:20210613
    ports:
      - "3000:3000"
    environment:
      - GIT_URL=https://github.com/alanapz/gitql-api.git
      - GIT_BRANCH=main
    volumes:
      - "gitql-api-data:/gitql-api"
      - "${GQL_ROOT}:/repos"

volumes:
  gitql-api-data:
    driver: local
